### ISSUE TITLE
No longer placing modified files into Upload Queue

### ISSUE THREAD

**Issue by scottyinzeo** [njpanderson/push#16] opened 2018-05-08 16:52 UTC
- Push version: 0.4.1
 - VS Code version: 1.23.0
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**
1. Open a Workspace/Project - /webroot/project1/
2. Create the initial Push config file (SFTP) - /webroot/.push.settings.json
```json
{
  "service": "SFTP",
  "SFTP": {
    "host": "webserver.com",
    "port": 22,
    "username": "myUsername",
    "privateKey": "/path/to/id_rsa",
    "root": "/webroot",
    "uploadQueue": true
  }
}
```
3. Modify a file within /webroot/project1/ or /webroot/ and save the file. The file does not appear within the Upload queue section of the side-panel

**Any other information?**

This used to work just fine until yesterday (that's when I noticed the issue). I've tried a clean install of VS Code with just the Push extension installed. I've also tried clean installing the prior version of VS Code (1.2.2) and ran into the same issue.

Uploading an open file using CTRL-ALT-U works just fine.

I'm new to VS Code so I'm not sure how I can help with debugging, but if you need any additional information, please let me know.

**Comment by njpanderson** [comment] 2018-05-08 17:31
Hey @scottyinzeo - thanks for the report! It's a duplicate of #15 so I'm going to close this one down.

**Closed by njpanderson** 2018-05-08 17:31 UTC
